<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StokTakip.Core\StokTakip.Core.csproj" />
    <ProjectReference Include="..\StokTakip.Service\StokTakip.Service.csproj" />
  </ItemGroup>

</Project>
